# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/data/programs/clion-2021.2.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/data/programs/clion-2021.2.3/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/data/workspace/mc/misc/craftingCalculator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/data/workspace/mc/misc/craftingCalculator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/data/programs/clion-2021.2.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/data/programs/clion-2021.2.3/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/data/workspace/mc/misc/craftingCalculator/CMakeFiles /home/data/workspace/mc/misc/craftingCalculator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/data/workspace/mc/misc/craftingCalculator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named craftingCalculator

# Build rule for target.
craftingCalculator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 craftingCalculator
.PHONY : craftingCalculator

# fast build rule for target.
craftingCalculator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/build
.PHONY : craftingCalculator/fast

src/Component.o: src/Component.cpp.o
.PHONY : src/Component.o

# target to build an object file
src/Component.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Component.cpp.o
.PHONY : src/Component.cpp.o

src/Component.i: src/Component.cpp.i
.PHONY : src/Component.i

# target to preprocess a source file
src/Component.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Component.cpp.i
.PHONY : src/Component.cpp.i

src/Component.s: src/Component.cpp.s
.PHONY : src/Component.s

# target to generate assembly for a file
src/Component.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Component.cpp.s
.PHONY : src/Component.cpp.s

src/IIngredient.o: src/IIngredient.cpp.o
.PHONY : src/IIngredient.o

# target to build an object file
src/IIngredient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/IIngredient.cpp.o
.PHONY : src/IIngredient.cpp.o

src/IIngredient.i: src/IIngredient.cpp.i
.PHONY : src/IIngredient.i

# target to preprocess a source file
src/IIngredient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/IIngredient.cpp.i
.PHONY : src/IIngredient.cpp.i

src/IIngredient.s: src/IIngredient.cpp.s
.PHONY : src/IIngredient.s

# target to generate assembly for a file
src/IIngredient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/IIngredient.cpp.s
.PHONY : src/IIngredient.cpp.s

src/Ingredient.o: src/Ingredient.cpp.o
.PHONY : src/Ingredient.o

# target to build an object file
src/Ingredient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Ingredient.cpp.o
.PHONY : src/Ingredient.cpp.o

src/Ingredient.i: src/Ingredient.cpp.i
.PHONY : src/Ingredient.i

# target to preprocess a source file
src/Ingredient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Ingredient.cpp.i
.PHONY : src/Ingredient.cpp.i

src/Ingredient.s: src/Ingredient.cpp.s
.PHONY : src/Ingredient.s

# target to generate assembly for a file
src/Ingredient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Ingredient.cpp.s
.PHONY : src/Ingredient.cpp.s

src/IngredientList.o: src/IngredientList.cpp.o
.PHONY : src/IngredientList.o

# target to build an object file
src/IngredientList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/IngredientList.cpp.o
.PHONY : src/IngredientList.cpp.o

src/IngredientList.i: src/IngredientList.cpp.i
.PHONY : src/IngredientList.i

# target to preprocess a source file
src/IngredientList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/IngredientList.cpp.i
.PHONY : src/IngredientList.cpp.i

src/IngredientList.s: src/IngredientList.cpp.s
.PHONY : src/IngredientList.s

# target to generate assembly for a file
src/IngredientList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/IngredientList.cpp.s
.PHONY : src/IngredientList.cpp.s

src/NbtData.o: src/NbtData.cpp.o
.PHONY : src/NbtData.o

# target to build an object file
src/NbtData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/NbtData.cpp.o
.PHONY : src/NbtData.cpp.o

src/NbtData.i: src/NbtData.cpp.i
.PHONY : src/NbtData.i

# target to preprocess a source file
src/NbtData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/NbtData.cpp.i
.PHONY : src/NbtData.cpp.i

src/NbtData.s: src/NbtData.cpp.s
.PHONY : src/NbtData.s

# target to generate assembly for a file
src/NbtData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/NbtData.cpp.s
.PHONY : src/NbtData.cpp.s

src/OreDictEntry.o: src/OreDictEntry.cpp.o
.PHONY : src/OreDictEntry.o

# target to build an object file
src/OreDictEntry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/OreDictEntry.cpp.o
.PHONY : src/OreDictEntry.cpp.o

src/OreDictEntry.i: src/OreDictEntry.cpp.i
.PHONY : src/OreDictEntry.i

# target to preprocess a source file
src/OreDictEntry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/OreDictEntry.cpp.i
.PHONY : src/OreDictEntry.cpp.i

src/OreDictEntry.s: src/OreDictEntry.cpp.s
.PHONY : src/OreDictEntry.s

# target to generate assembly for a file
src/OreDictEntry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/OreDictEntry.cpp.s
.PHONY : src/OreDictEntry.cpp.s

src/OreDictIngredient.o: src/OreDictIngredient.cpp.o
.PHONY : src/OreDictIngredient.o

# target to build an object file
src/OreDictIngredient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/OreDictIngredient.cpp.o
.PHONY : src/OreDictIngredient.cpp.o

src/OreDictIngredient.i: src/OreDictIngredient.cpp.i
.PHONY : src/OreDictIngredient.i

# target to preprocess a source file
src/OreDictIngredient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/OreDictIngredient.cpp.i
.PHONY : src/OreDictIngredient.cpp.i

src/OreDictIngredient.s: src/OreDictIngredient.cpp.s
.PHONY : src/OreDictIngredient.s

# target to generate assembly for a file
src/OreDictIngredient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/OreDictIngredient.cpp.s
.PHONY : src/OreDictIngredient.cpp.s

src/Recipe.o: src/Recipe.cpp.o
.PHONY : src/Recipe.o

# target to build an object file
src/Recipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Recipe.cpp.o
.PHONY : src/Recipe.cpp.o

src/Recipe.i: src/Recipe.cpp.i
.PHONY : src/Recipe.i

# target to preprocess a source file
src/Recipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Recipe.cpp.i
.PHONY : src/Recipe.cpp.i

src/Recipe.s: src/Recipe.cpp.s
.PHONY : src/Recipe.s

# target to generate assembly for a file
src/Recipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/Recipe.cpp.s
.PHONY : src/Recipe.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/craftingCalculator.dir/build.make CMakeFiles/craftingCalculator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... craftingCalculator"
	@echo "... src/Component.o"
	@echo "... src/Component.i"
	@echo "... src/Component.s"
	@echo "... src/IIngredient.o"
	@echo "... src/IIngredient.i"
	@echo "... src/IIngredient.s"
	@echo "... src/Ingredient.o"
	@echo "... src/Ingredient.i"
	@echo "... src/Ingredient.s"
	@echo "... src/IngredientList.o"
	@echo "... src/IngredientList.i"
	@echo "... src/IngredientList.s"
	@echo "... src/NbtData.o"
	@echo "... src/NbtData.i"
	@echo "... src/NbtData.s"
	@echo "... src/OreDictEntry.o"
	@echo "... src/OreDictEntry.i"
	@echo "... src/OreDictEntry.s"
	@echo "... src/OreDictIngredient.o"
	@echo "... src/OreDictIngredient.i"
	@echo "... src/OreDictIngredient.s"
	@echo "... src/Recipe.o"
	@echo "... src/Recipe.i"
	@echo "... src/Recipe.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

